service: ml-pipeline-template

plugins:
  - serverless-offline

provider:
  name: aws
  profile: default
  stage: dev
  region: ap-northeast-1
  memorySize: 2048
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:ListBucket'
          Resource:
            - "*"
        - Effect: 'Allow'
          Action:
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
          Resource:
            - "*"
  environment:
    TZ: Asia/Tokyo

functions:
  crawl:
    image:
      name: "${env:IMAGE_URL}"
      command:
        - crawl.crawl
    events:
      - schedule: cron(0 0 * * *)
    timeout: 1200
    environment:
      BUCKET_NAME: ${env:BUCKET_NAME}
